### ISSUE TITLE
Deploying Nuxt.js app to Azure

### ISSUE THREAD

**Issue by markholdt** [azurecasts/azurecasts.com#2]
Rob have been a big fan of yours for a long time! Love what you guys are doing with AzureCasts.com. The quality of videos reminds me of Tekpub.

So here is a scenario I have personally been struggling with on Azure. (Sidenote: deployed a Nuxt.js on multiple other cloud platforms very easily)

**Issue**: Deploying a Nuxt.js universal app on Azure is uber difficult / or I am being stupid

**Background**: Nuxt.js is a popular & opinionated framework 'on top of' Vue with lots of modules already built in. It presents a structured best-practice layout so a newbie does not have to think about how to structure his/her project.

It is super easy to start creating a Nuxt app. https://nuxtjs.org/guide/installation

I'd love a short 15min video on how to deploy Nuxt.js app on Azure.

Keep up the great work.

**Comment by robconery** [comment]
Great idea - and thank you! @burkeholland just did a static site deployment vid which I just published - have a look and let me know if this works for you.

https://azurecasts.com/2019/06/07/deploying-a-static-site/

**Comment by burkeholland** [comment]
This is a great idea! And no, you are definitely not stupid. Azure is powerful, but that makes it hard to figure out the simple things some times. I've spent hours doing nothing but deploying code from the Node.js Getting Started guide and wondering why it doesn't work.

The static site video that @robconery mentions above will work for static sites (no server-side build). The SSR stuff would work on AppService and you could have a build step executed there as well. Which scenario sounds better to you?

**Comment by markholdt** [comment]
Wow amazing that you guys are replying to my issue . I never thought I’d get a response so thank you both. 

Thank you for the video on static site deployment. That is helpful.

I have an ongoing saga with trying to deploy SSR. I’m a newbie on Azure and most stuff simply just works. But I’m struggling with this one & have actually given up . If you indeed make a video on SSR deployment and how to do a build step on app service; I’d be super grateful !

Thanks 
Mark

**Comment by burkeholland** [comment]
Yeah! I can do that!

I was just wondering what I was going to do next, so I think we can do "Deploying An SSR App To Azure" or something along those lines.

I just pulled down Nuxt today and started playing with it. Very cool stuff!

**Comment by burkeholland** [comment]
Hey @markholdt!

I'm working on this episode now. In the meantime, here's what you need...

1. Make sure you are running on a Linux site with Node version 10.14.1. That version is important because that's where the new Orxy build tool works.
2. Make sure you have a `.deployment` file in your project with the setting that tells Oryx to run the build process...

    ````
    [config]
    SCM_DO_BUILD_DURING_DEPLOYMENT=true
    ````

    This will cause Oryx to run `npm install` followed by `npm run build`.

3. You gotta bind to the donut address (all zeros) because Nuxt tries to bind to localhost by default and Azure ain't havin' it. Add the following Application Setting to your site...

    ```
    HOST=0.0.0.0
    ````

That should get you up and running. You can work with earlier versions of Node, but you can't run the `npm run build` step if you do. Let me know if this works for you!

**Comment by markholdt** [comment]
This is amazing feedback. Thank you!

I was missing step 1 & 2 in my deployment process . That was the insight I needed !

**Comment by verschaevesiebe** [comment]
@burkeholland Hi man ! Glad someone is here to provide some decent feedback.
I've been playing around with nuxt SSR for the last 5 days and still haven't figured out on how to deploy it in a proper way.

What seems to bother me is that i'm deploying it on a Windows service plan. The main reason why i'm using the windows plan is because there i'm having a extension for Let's encrypt which renews my monthly SSL certificates. I have been trying to deploy everything with Kudu and when i check the logging everything seems to go fine until i'm running the "nuxt start" command. It seems like azure aint having it. They're asking me to do a startup command like "node node_modules/nuxt/bin/nuxt.js but in my opinion that just runs the development server. If i check logging it clearly says that it's up and running on a localport (something with 10.0.4...:3000) but when i seem to surf to my site it's just a blank 500 error. Would you be able to give me a guide on how to do deploy the Nuxt SSR latest on a Windows app service plan ?

Greatly appreciating everything you guys do.
Thanks

**Comment by burkeholland** [comment]
Yeah - I need to get a video up on this. I keep telling @robconery I'm going to do it and then I never do it.

In the meantime, I wrote up the script of the video and made it a blog post. Hopefully this will point you in the right direction. The first part of the post covers Linux, the second parts covers Windows.

https://burkeknowswords.com/thank-u-nuxt-d414cba80c59

**Comment by verschaevesiebe** [comment]
Hi yes i've read that post and followed it but haven't been able to get it working. As i'm able to tell you use the server/index.js as a starters file in that demo so i recon u are using the express template ?

It would be great to provide the commands you've made beforehand just to create it.
Again thank you for your efforts that you've been putting in to your videos.
